Repository go-vela/sdk-go, pull requests merged in 2019-12, with the labels that each got.

#16 Release v0.2.0-rc2
  go.mod
  go.sum
Labels: enhancement

#17 Update go mod dependencies
  go.mod
  go.sum
Labels: enhancement

#18 Add Actions pipeline for changelog
  .chglog/CHANGELOG.tpl.md
  .chglog/config.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: feature

#19 ci: ignore release candidate for changelog
  .github/workflows/release.yml
Labels: enhancement

#20 feat(build): add email and link fields
  go.mod
  go.sum
  vela/build_test.go
Labels: enhancement

#21 chore: update go-vela dependencies
  go.mod
  go.sum
Labels: feature

#22 ci: switch from coveralls to codecov
  .github/README.md
  .github/workflows/test.yml
Labels: enhancement

#23 ci: add explicit configuration for automation
  .golangci.yml
  codecov.yml
Labels: enhancement

#24 refactor: fix linter errors
  vela/build.go
  vela/build_test.go
  vela/client.go
  vela/client_test.go
  vela/log.go
  vela/log_test.go
  vela/login.go
  vela/repo.go
  vela/repo_test.go
  vela/secret.go
  vela/secret_test.go
  vela/service.go
  vela/service_test.go
  vela/step.go
  vela/step_test.go
Labels: enhancement

#25 chore: update for v0.2.0
  go.mod
  go.sum
Labels: dependencies

#26 ci(linters): update funlen linter settings
  .golangci.yml
Labels: enhancement
